# Generated by Django 5.2.15 on 2026-06-18 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-ідентифікатор')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-ідентифікатор')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна, грн')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обкладинка')),
                ('book_type', models.CharField(choices=[('print', 'Друкована'), ('electronic', 'Електронна')], default='print', max_length=20, verbose_name='Тип книги')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Запас на складі')),
                ('digital_file', models.FileField(blank=True, null=True, upload_to='ebooks/', verbose_name='Файл книги')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна для продажу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='catalog_boo_slug_7fab6a_idx'), models.Index(fields=['book_type'], name='catalog_boo_book_ty_3197b6_idx')],
            },
        ),
    ]
